[package]
name = "rust_tokenizer_example"
version = "0.1.0"
edition = "2024"

[dependencies]
tokenizers = "0.15"
hf-hub = { version = "0.3", features = ["tokio"] }
tokio = { version = "1.0", features = ["full"] }
